Site/Analysis/routes.py
from flask import Flask, render_template, redirect, request, url_for, Blueprint, abort, jsonify # importing libraries from framework
import uuid 
from ..models import * 
from Site import db, app 
import datetime
from Site.editor.form import NotificationForm
import os
from dotenv import load_dotenv
import requests 

load_dotenv()

# registering blueprint 
analysis = Blueprint('analysis', __name__)

def handle_prediction_view(template_name):
    form = NotificationForm()
    
    if form.validate_on_submit():
        notify = Notification()
        notify.name = form.name.data
        notify.email = form.email.data
        db.session.add(notify)
        db.session.commit()
        
        return redirect(url_for('edit.home'))
    
    return render_template(template_name, form=form)

@analysis.route('/in-form-teams', methods=['GET', 'POST'])
def mostInFormTeams():
    in_form = InForm.query.order_by(InForm.win_percent.desc()).all()[:25]

    return render_template( 'informteam.html', in_form=in_form)

@analysis.route('/betting-tips', methods=['GET', 'POST'])
def bettingTips():
    betting_tips = BettingTips.query.order_by(BettingTips.date_uploaded.desc()).all()[:25]

    return render_template('betting-tips.html', betting_tips=betting_tips)

@analysis.route('/teams-with-high-scoring-stats', methods=['GET', 'POST'])
def teamsWithHighGoalStats():
    high_scoring = HighScoring.query.order_by(HighScoring.scoring_rate.desc()).all()[:25]

    return render_template('high-scoring-stats.html', high_scoring=high_scoring)

@analysis.route('/both-team-score-tips', methods=['GET', 'POST'])
def bothTeamScoreTips():
    bts_tip = Bts.query.order_by(Bts.prediction.desc()).all()[:25]

    return render_template( 'both-team-score.html', bts_tip=bts_tip)

@analysis.route('/teams-with-high-conceding-rate', methods=['GET', 'POST'])
def teamsWithHighConcedingRate():
    high_conceding = HighConceding.query.order_by(HighConceding.conceding_rate.desc()).all()[:25]

    return render_template('high-conceding.html', high_conceding=high_conceding)

@analysis.route('/teams-to-bet-against', methods=['GET', 'POST'])
def teamsToBetAgainst():
    betagainst = BetAgainst.query.order_by(BetAgainst.date_uploaded.desc()).all()[:25]

    return render_template( 'bet-against.html', betagainst=betagainst)

@analysis.route('/teams/statistics', methods=['GET', 'POST'])
def team_statistics():

    return render_template( 'statistics.html')

@analysis.route('/Home/Away', methods=['GET', 'POST'])
def home_or_away():
    anywin = H_or_A.query.order_by(H_or_A.date_uploaded.desc()).all()[:25]

    return render_template( 'any_win.html', anywin=anywin)

@analysis.route('/draws/prediction', methods=['GET', 'POST'])
def championshipDraw():
    return render_template( 'championship-draws.html')


@analysis.route('/search', methods=['GET', 'POST'])
def searchfile():
    return render_template('statistics.html')


@analysis.route('/searche', methods=['POST'])
def search():
    data = request.form.get('text')
    results = Teams.query.filter(Teams.name.ilike(f'%{data}%')).all()
    teams_schema = TeamsSchema(many=True)
    res = teams_schema.dump(results)
    return jsonify(res)



@analysis.route('/<string:name>', methods=['GET'])
def team_detail(name):
    team = Teams.query.filter_by(name=name).first()
    team_key = Teamkey.query.filter_by(name=team.name).first()
    if team_key:
        url = f"https://apiv3.apifootball.com/?action=get_H2H&firstTeamId={team_key.key}&secondTeamId={151}&APIkey={os.environ.get('Api_Key')}"
        extend = []
        response = requests.get(url)
        if response.status_code == 200:
            data = response.json()
            
            for i in data["firstTeam_lastResults"]:
                data_json = {
                    "league_name" : i["league_name"],
                    "match_date" : i["match_date"],
                    "hometeam" : i["match_hometeam_name"],
                    "awayteam" : i["match_awayteam_name"],
                    "hometeam_score" : i["match_hometeam_score"],
                    "awayteam_score" : i["match_awayteam_score"],
                    "hometeam_halftime_score" : i["match_hometeam_halftime_score"],
                    "awayteam_halftime_score" : i["match_awayteam_halftime_score"]
                }
                extend.append(data_json)
                
                print(extend)

        return render_template('team.html',team=team, extend=extend)

@analysis.route('/livescore')
def live():
    return render_template('livescore.html')  

@analysis.route('/teams/performance')
def team_performance():
    return render_template('team_performance.html')  

@analysis.route('/fixture/prediction')
def fixture_prediction():
    betting_tips = BettingTips.query.order_by(BettingTips.date_uploaded.desc()).all()[:25]

    return render_template('pred_home.html', betting_tips=betting_tips)

Site/editor/routes.py
# importing libraries
from flask import Flask, render_template, redirect, request, url_for, Blueprint, abort, jsonify # importing libraries from framework
import uuid # using random string generator
from ..models import * # importing classes from models.py 
from Site import db, app, io # importing database and app configuration from folder package
import os
from datetime import datetime, timedelta
import time
from Site.models import InForm, BetAgainst, BettingTips, Bts, HighScoring, HighConceding, Teams
from .form import RandomPickForm
import requests
from flask_socketio import emit

from dotenv import load_dotenv

load_dotenv()
edit = Blueprint('edit', __name__)



@edit.route('/', methods=['GET','POST'])
def home():
    seven_days_ago = datetime.now() - timedelta(days=7)
    pick = RandomPrediction.query.all()
    prediction = RandomPrediction.query.filter(RandomPrediction.date_uploaded >= seven_days_ago).all()
    form = RandomPickForm()
    if form.validate_on_submit():
        notify = RandomPrediction()
        notify.content = form.content.data
        notify.country = form.country.data
        notify.league = form.league.data
        db.session.add(notify)

        db.session.commit()

        return redirect(url_for('edit.home'))
    return render_template('index.html', pick=pick, form=form)



@edit.route('/contact')
def contact():

    return render_template('contact.html')

@edit.route('/create_tables')
def create_tables():
    with app.app_context():
        db.drop_all()
        db.create_all()
    return 'Database tables created successfully'

@edit.route('/home/away/previous')
def last_pred():
    data = H_or_A.query.filter_by(week=week).all()
    bts_data = Bts.query.filter_by(week=week).all()
    bpicks_data = BettingTips.query.filter_by(week=week).all()


    return render_template('previous.html', data=data, bts_data=bts_data, bpicks_data=bpicks_data)



def get_date_strings():
    today_date = datetime.now().date() + timedelta(days=1)
    one_day_from_today = today_date + timedelta(days=2)
    today_date_str = today_date.strftime('%Y-%m-%d')
    one_day_from_today_str = one_day_from_today.strftime('%Y-%m-%d')
    return today_date_str, one_day_from_today_str

@edit.route('/fixture')
@edit.route('/fixture/<date_type>')
def fixture(date_type=None):
    today_date_str, one_day_from_today_str = get_date_strings()

    if date_type == 'tomorrow':
        two_days_from_today = datetime.strptime(one_day_from_today_str, '%Y-%m-%d') + timedelta(days=1)
        two_days_from_today_str = two_days_from_today.strftime('%Y-%m-%d')

        api_url = f"https://apiv3.apifootball.com/?action=get_events&from={one_day_from_today_str}&to={two_days_from_today_str}&APIkey={os.environ.get('Api_Key')}"
        odds_url = f"https://apiv3.apifootball.com/?action=get_odds&from=2023-09-12&to=2023-09-13&APIkey={os.environ.get('Api_Key')}"
    else:
        api_url = f"https://apiv3.apifootball.com/?action=get_events&from={today_date_str}&to={one_day_from_today_str}&APIkey={os.environ.get('Api_Key')}"
        odds_url = f"https://apiv3.apifootball.com/?action=get_odds&from=2023-09-11&to=2023-09-12&APIkey={os.environ.get('Api_Key')}"

    response = requests.get(api_url)
    response_odds = requests.get(odds_url)

    if response.status_code == 200 and response_odds.status_code == 200:
        data = response.json()
        extracted_data = []
        for match_data in data:
            data = {
                "country_name": match_data["country_name"],
                "league_name": match_data["league_name"],
                "league_year": match_data["league_year"],
                "match_date": match_data["match_date"],
                "match_time": match_data["match_time"],
                "match_hometeam_name": match_data["match_hometeam_name"],
                "match_awayteam_name": match_data["match_awayteam_name"],
                "match_stadium": match_data["match_stadium"],
                "match_round": match_data["match_round"],
                "stage_name": match_data["stage_name"]
            }
            extracted_data.append(data)
        return render_template('fixture.html', extracted_data=extracted_data)
    else:
        return "Error: Unable to fetch data from the API", response.status_code


@io.on('connect')
def handle_connect():
    APIkey = os.environ.get('Api_Key')
    socket_url = f'wss://wss.apifootball.com/livescore?Widgetkey={APIkey}&timezone=+01:00'
    
    def on_message(message):
        emit('data', message)  

    socket = None

    try:
        socket = io.AsyncClient()
        socket.connect(socket_url)

        @socket.on('message')
        def handle_message(data):
            on_message(data)

        socket.wait()
    except Exception as e:
        print(f"WebSocket connection error: {e}")
    finally:
        if socket:
            socket.disconnect()

Site/templates/any_win.html
{% extends 'pred.html' %}
{% block content %}


<div id="about">
    <div class="container">
        <div class="row">

            <div class="col-xl-10 col-lg-10 col-md-12 col-sm-12">
                <div class="about-box">
                    <h3 class="in_form"> Any Team To Win</h3>
                    <table>
                    
                        <thead>
                            <tr>
                                <th scope="col">Fixture</th>
                                <th scope="col">League</th>
                                <th scope="col">Prediction</th>
                            </tr>
                        </thead>
                        {% for picks in anywin %}
                        <tbody>
                            <tr>
                                <td data-label="Team">{{ picks.fixture }}</td>
                                <td data-label="League">{{ picks.league }}</td>
                                <td data-label="prediction">{{ picks.prediction }}</td>
                            
                            </tr>
                    
                        </tbody>
                        {% endfor %}
                    </table>
                </div>
                <h6><a href="{{url_for('edit.last_pred', data=data)}}"> Last Prediction </a></h6>
            </div>
        </div>

    </div>
</div>

{%endblock content%}

Site/templates/base.html
<!DOCTYPE html>
<html lang="en">

<head>
    <!-- basic -->
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <!-- mobile metas -->
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="viewport" content="initial-scale=1, maximum-scale=1">
    <!-- site metas -->
    <title>BettingFixed</title>
    <meta name="keywords" content="">
    <meta name="description" content="">
    <meta name="author" content="">
    <!-- bootstrap css -->
    <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='css/bootstrap.min.css') }}">
    <!-- style css -->
    <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='css/style.css') }}">
    <!-- Responsive-->
    <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='css/responsive.css') }}">
    <!-- fevicon -->
    <link rel="icon" type="image/gif" href="{{ url_for('static', filename='images/fevicon.png') }}">
    <!-- Scrollbar Custom CSS -->
    <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='css/jquery.mCustomScrollbar.min.css') }}">
    <!-- Tweaks for older IEs-->
    <link rel="stylesheet" href="https://netdna.bootstrapcdn.com/font-awesome/4.0.3/css/font-awesome.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/fancybox/2.1.5/jquery.fancybox.min.css"
        media="screen">
    <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='css/modal.css') }}">
    <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js"></script>
      <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script><![endif]-->

    <link rel="apple-touch-icon" sizes="180x180" href="{{ url_for('static', filename='/favicon/apple-touch-icon.png') }}">
    <link rel="icon" type="image/png" sizes="32x32" href="{{ url_for('static', filename='favicon/favicon-32x32.png') }}">
    <link rel="icon" type="image/png" sizes="16x16" href="{{ url_for('static', filename='favicon/favicon-16x16.png') }}">
    <link rel="manifest" href="static/favicon/site.webmanifest">
    
</head>
<!-- body -->

<body class="main-layout">
    <!-- loader  -->
    
    <!-- end loader -->
    <!-- header -->
    <header>
        <!-- header inner -->
        <div class="header-top2">
            <div class="header2">
                <div class="container-fluid">
                    <div class="row">
                        <div class="col-xl-3 col-lg-3 col-md-3 col-sm-3 col logo_section">
                            <div class="full">
                                <div class="center-desk">
                                    <div class="logo" >
                                        <a style="font-size: 34px;" href="{{ url_for('edit.home') }}"><img style="height: 30px;" alt='' src="static/favicon/favicon-32x32.png">BettingFixed</a>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class="col-xl-9 col-lg-9 col-md-9 col-sm-9">
                            <div class="menu-area">
                                <div class="limit-box">
                                    <nav class="main-menu">
                                        <ul class="menu-area-main">
                                            <li><a href="{{ url_for('analysis.team_performance') }}" class="deg">Team Performance</a></li> |
                                            <li><a href="{{ url_for('analysis.fixture_prediction') }}" class="deg">Prediction</a> </li> |
                                            <li><a href="{{ url_for('analysis.team_statistics')}}" class="deg">Team Statistics</a> </li> |
                                            <li  class="active"><a href="{{ url_for('edit.fixture') }}" class="deg">Fixtures</a></li>

                                        </ul>
                                    </nav>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <!-- end header inner -->

            <!-- end header -->
            <section class="slider_section">
                <div class="banner_main">

                    <div class="container">

                        <div class="row">
                            <div class="col-xl-6 col-lg-6 col-md-6 col-sm-12 ">
                                <div class="text-bg">
                                    <h1>Get  <br> <strong class="b_bold">Betting Tips </strong></h1>
                                   
                                    <a href="https://web.bet9ja.com/Sport/Default.aspx">Book Online</a>
                                </div>
                            </div>
                            <div class="col-xl-6 col-lg-6 col-md-6 col-sm-12">
                                <div class="text-img">
                                    <figure><img src="static/images/hpg-logo-preview.png" /></figure>


                                </div>
                            </div>
                        </div>
                    </div>
                </div>
        </div>
        </section>
        </div>
        </div>
    </header>


{% with messages = get_flashed_messages(with_categories=true) %}
{% if messages %}
{% for category, message in messages %}

<div class="alert alert-{{ category }}">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
        <span aria-hidden="true">&times;</span>
    </button>
    {{ message }}
</div>
{% endfor %}
{% endif %}
{% endwith %}
{% block content %}{% endblock %}
    <!--  footer -->
    <footr>
        <div class="footer top_layer ">
            <div class="container">
                <div class="row">
             
                    <div class="col-xl-8 col-lg-8 col-md-12 col-sm-12 ">
                        <div class="row">
                            <div class="col-lg-4 col-md-4 col-sm-6">
                                <div class="address">
                                    <h3 style="font-size: 15px;">Menu</h3>
                                    <ul class="menu-area-main">
                                        <li><a href="{{ url_for('analysis.mostInFormTeams') }}" class="deg">In Form Teams</a></li>
                                        <li><a href="{{ url_for('analysis.bettingTips') }}" class="deg">Betting Tips</a></li>
                                        <li><a href="{{ url_for('analysis.teamsWithHighGoalStats') }}" class="deg">High Goal Scoring Teams</a></li>
                                        <li><a href="{{ url_for('analysis.bothTeamScoreTips') }}" class="deg">Both Teams To Score Tips</a></li>
                                        <li><a href="{{ url_for('analysis.teamsWithHighConcedingRate') }}" class="deg">High Goal Conceding Teams</a></li>
                                        <li class="active"><a href="{{ url_for('analysis.home_or_away') }}" class="deg"> Home Or Away</a></li>
                                        <li><a href="{{ url_for('analysis.championshipDraw') }}" class="deg">Draw/Under 2.5</a></li>
                                        <li><a href="{{ url_for('analysis.team_statistics')}}" class="deg">Team Statistics</a></li>

                                    </ul>
                                </div>
                            </div>
                           
                            <div class="col-lg-4 col-md-4 col-sm-6">
                                <div class="address">
                                    <h3 style="font-size: 15px;">Menu</h3>
                                    <ul class="Menu_footer">
                                        <li><a href="{{ url_for('analysis.mostInFormTeams') }}" style="font-size: 13px;">In Form Teams</a></li>
                                        <li><a href="{{ url_for('analysis.bettingTips') }}" style="font-size: 13px;">Betting Tips</a></li>
                                        <li><a href="{{ url_for('analysis.teamsWithHighGoalStats') }}" style="font-size: 13px;">High Goal Scoring Teams</a></li>
                                        <li><a href="{{ url_for('analysis.bothTeamScoreTips') }}" style="font-size: 13px;">Both Teams To Score Tips</a></li>
                                        <li><a href="{{ url_for('analysis.teamsWithHighConcedingRate') }}" style="font-size: 13px;">High Goal Conceding Teams</a></li>
                                        <li class="active"><a href="{{ url_for('analysis.home_or_away') }}" class="deg"> Home Or Away</a></li>
                                        <li><a href="{{ url_for('analysis.championshipDraw') }}" style="font-size: 13px;">Draw/Under 2.5</a></li>
                                        <li><a href="{{ url_for('analysis.team_statistics')}}" style="font-size: 13px;">Team Statistics</a></li>

                                    </ul>
                                </div>
                            </div>

                        </div>
                    </div>
                    
                    
                </div>

            </div>
            <div class="copyright">
                <div class="container">
                    <p>© 2023 All Rights Reserved.</p>
                </div>
            </div>
        </div>
    </footr>
    <!-- end footer -->
    <!-- Javascript files-->
    <script src= "{{ url_for('static', filename='js/jquery.min.js') }}"></script>
    <script src= "{{ url_for('static', filename='js/popper.min.js') }}"></script>
    <script src= "{{ url_for('static', filename='js/bootstrap.bundle.min.js') }}"></script>
    <script src= "{{ url_for('static', filename='js/jquery-3.0.0.min.js') }}"></script>
    <script src= "{{ url_for('static', filename='js/plugin.js') }}"></script>
    <script src= "{{ url_for('static', filename='js/jquery.mCustomScrollbar.concat.min.js') }}"></script>
    <script src= "{{ url_for('static', filename='js/custom.js') }}"></script>

</body>

</html>

Site/templates/fixture.html
{% extends 'layout.html' %}
{% block content %}

<div id="about">
    <div class="container">
        <div class="row">

            <div class="col-xl-10 col-lg-10 col-md-12 col-sm-12">
                <div class="about-box">
                    <h3 class="in_form">Today Fixtures</h3>
                    
                    <table>
                    
                        <thead>
                            <tr>
                             
                            </tr>
                        </thead>
                        <tbody>
                            <tr>
                                    <td data-label="Team"><a href="{{url_for('edit.fixture', date_type='tomorrow')}}"> Tomorrow Fixture </a></td>
                                    <td data-label="League"> <a href="{{url_for('analysis.live')}}"> Live Matches</a> </td>                            
                            </tr>
                    
                        </tbody>
                    </table>
                
                    <table>
                    
                        <thead>
                            <tr>
                                <th scope="col">Fixture</th>
                                <th scope="col">League</th>
                            </tr>
                        </thead>
                        {% for match in extracted_data %}
                        <tbody>
                            <tr>
                                    <td data-label="Team">{{ match.match_hometeam_name }} vs {{ match.match_awayteam_name }}</td>
                                    <td data-label="League">{{ match.league_name }} </td>                            
                            </tr>
                    
                        </tbody>
                        {% endfor %}
                    </table>
                </div>
            </div>
        </div>

    </div>
</div>

{%endblock content%}

Site/templates/layout.html
<!DOCTYPE html>
<html lang="en">

<head>
    <!-- basic -->
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <!-- mobile metas -->
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="viewport" content="initial-scale=1, maximum-scale=1">
    <!-- site metas -->
    <title>BettingFixed</title>
    <meta name="keywords" content="">
    <meta name="description" content="">
    <meta name="author" content="">
    <!-- bootstrap css -->
    <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='css/bootstrap.min.css') }}">
    <!-- style css -->
    <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='css/style.css') }}">
    <!-- Responsive-->
    <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='css/responsive.css') }}">
    <!-- fevicon -->
    <link rel="icon" type="image/gif" href="{{ url_for('static', filename='images/fevicon.png') }}">
    <!-- Scrollbar Custom CSS -->
    <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='css/jquery.mCustomScrollbar.min.css') }}">
    <!-- Tweaks for older IEs-->
    <link rel="stylesheet" href="https://netdna.bootstrapcdn.com/font-awesome/4.0.3/css/font-awesome.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/fancybox/2.1.5/jquery.fancybox.min.css"
        media="screen">
    <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='css/modal.css') }}">
    <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js"></script>
      <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script><![endif]-->

    <link rel="apple-touch-icon" sizes="180x180" href="{{ url_for('static', filename='/favicon/apple-touch-icon.png') }}">
    <link rel="icon" type="image/png" sizes="32x32" href="{{ url_for('static', filename='favicon/favicon-32x32.png') }}">
    <link rel="icon" type="image/png" sizes="16x16" href="{{ url_for('static', filename='favicon/favicon-16x16.png') }}">
    <link rel="manifest" href="static/favicon/site.webmanifest">
    
</head>
<!-- body -->

<body class="main-layout">
    <!-- loader  -->
    
    <!-- end loader -->
    <!-- header -->
    <header>
        <!-- header inner -->
        <div class="header-top">
            <div class="header">
                <div class="container-fluid">
                    <div class="row">
                        <div class="col-xl-3 col-lg-3 col-md-3 col-sm-3 col logo_section">
                            <div class="full">
                                <div class="center-desk">
                                    <div class="logo" >
                                        <a style="font-size: 17px;" href="{{ url_for('edit.home') }}"><img style="height: 17px;" alt='' src="{{ url_for('static', filename='favicon/favicon-32x32.png') }}">BettingFixed</a>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class="col-xl-9 col-lg-9 col-md-9 col-sm-9">
                            <div class="menu-area">
                                <div class="limit-box">
                                    <nav class="main-menu">
                                        <ul class="menu-area-main">
                                            <li><a href="{{ url_for('analysis.team_performance') }}" class="deg">Team Performance</a></li> |
                                            <li><a href="{{ url_for('analysis.fixture_prediction') }}" class="deg">Prediction</a> </li> |
                                            <li><a href="{{ url_for('analysis.team_statistics')}}" class="deg">Team Statistics</a> </li> |
                                            <li><a href="{{ url_for('edit.fixture') }}" class="deg">Fixtures</a></li>

                                        </ul>
                                    </nav>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <!-- end header inner -->

        </div>
        </div>
    </header>


{% with messages = get_flashed_messages(with_categories=true) %}
{% if messages %}
{% for category, message in messages %}

<div class="alert alert-{{ category }}">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
        <span aria-hidden="true">&times;</span>
    </button>
    {{ message }}
</div>
{% endfor %}
{% endif %}
{% endwith %}
{% block content %}{% endblock %}
    <!--  footer -->
    <footr>
        <div class="footer top_layer ">
            <div class="container">
                <div class="row">
               
                    <div class="col-xl-8 col-lg-8 col-md-12 col-sm-12 ">
                        <div class="row">
                            <div class="col-lg-4 col-md-4 col-sm-6">
                                <div class="address">
                                    <h3 style="font-size: 15px;">Menu</h3>
                                    <ul class="menu-area-main">
                                        <li><a href="{{ url_for('analysis.mostInFormTeams') }}" class="deg">In Form Teams</a></li>
                                        <li><a href="{{ url_for('analysis.bettingTips') }}" class="deg">Betting Tips</a></li>
                                        <li><a href="{{ url_for('analysis.teamsWithHighGoalStats') }}" class="deg">High Goal Scoring Teams</a></li>
                                        <li><a href="{{ url_for('analysis.bothTeamScoreTips') }}" class="deg">Both Teams To Score Tips</a></li>
                                        <li><a href="{{ url_for('analysis.teamsWithHighConcedingRate') }}" class="deg">High Goal Conceding Teams</a></li>
                                        <li class="active"><a href="{{ url_for('analysis.home_or_away') }}" class="deg"> Home Or Away</a></li>
                                        <li><a href="{{ url_for('analysis.championshipDraw') }}" class="deg">Draw/Under 2.5</a></li>
                                        <li><a href="{{ url_for('analysis.team_statistics')}}" class="deg">Team Statistics</a></li>

                                    </ul>
                                </div>
                            </div>
                           
                        </div>
                    </div>
                    
                </div>

            </div>
            <div class="copyright">
                <div class="container">
                    <p>© 2023 All Rights Reserved.</p>
                </div>
            </div>
        </div>
    </footr>
    <!-- end footer -->
    <!-- Javascript files-->
    <script src= "{{ url_for('static', filename='js/jquery.min.js') }}"></script>
    <script src= "{{ url_for('static', filename='js/popper.min.js') }}"></script>
    <script src= "{{ url_for('static', filename='js/bootstrap.bundle.min.js') }}"></script>
    <script src= "{{ url_for('static', filename='js/jquery-3.0.0.min.js') }}"></script>
    <script src= "{{ url_for('static', filename='js/plugin.js') }}"></script>
    <script src= "{{ url_for('static', filename='js/jquery.mCustomScrollbar.concat.min.js') }}"></script>
    <script src= "{{ url_for('static', filename='js/custom.js') }}"></script>
</body>

</html>

Site/templates/post.html
<h3> {{legend }} </h3>
<form method="POST" action="" enctype="multipart/form-data">
    {{ form.hidden_tag() }}
    {{ form.content }}
    {{ form.country }}
    {{ form.league }}
    {{ form.submit }}
</form>

